spring:
  datasource:
    url: jdbc:mysql://172.17.02:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  
  jackson:
        serialization:
            fail-on-empty-beans: false
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always