server:
  servlet:
    context-path: /api
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jackson:
        serialization:
            fail-on-empty-beans: false
  jpa:
    database-platform: ${MYSQL_DIALECT}
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always